#!/bin/bash
echo "=== Redis Connection Troubleshooting Guide ==="
echo ""
echo "Your Laravel app is now using database cache to avoid connection issues."
echo "To enable Redis again when it's properly set up, follow these steps:"
echo ""
echo "1. FIRST - Start Redis in WSL:"
echo "   wsl"
echo "   sudo service redis-server start"
echo "   # OR if using systemd:"
echo "   sudo systemctl start redis-server"
echo ""
echo "2. VERIFY Redis is running in WSL:"
echo "   redis-cli ping"
echo "   # Should return: PONG"
echo ""
echo "3. TEST connection from Windows:"
echo "   php test_redis.php"
echo "   # Should show: Redis connection: SUCCESS"
echo ""
echo "4. IF connection works, update .env:"
echo "   CACHE_STORE=redis"
echo "   CACHE_DRIVER=redis"
echo ""
echo "5. THEN clear Laravel cache:"
echo "   php artisan config:clear"
echo "   php artisan cache:clear"
echo ""
echo "=== Common Redis Issues on WSL ==="
echo "• Redis service stopped: sudo service redis-server start"
echo "• Firewall blocking: Make sure WSL ports are accessible"
echo "• WSL networking: Try 'wsl --shutdown' then restart WSL"
echo "• Redis config: Check /etc/redis/redis.conf for bind settings"
echo ""
echo "Your rate limiting is now working with database cache!"