<?php

namespace Database\Factories;

use App\Models\Word;
use Illuminate\Database\Eloquent\Factories\Factory;

class WordFactory extends Factory
{
    protected $model = Word::class;

    public function definition(): array
    {
        // This factory should not be used for meaningful data
        // Use the WordSeeder instead for real vocabulary
        $topics = [
            'Technology', 'Business', 'Travel', 'Food', 'Health', 'Education', 
            'Sports', 'Entertainment', 'Science', 'Nature', 'Family', 'Work',
            'Shopping', 'Transportation', 'Weather', 'Emotions', 'Hobbies', 'Culture'
        ];

        $word = 'placeholder_' . $this->faker->unique()->numberBetween(1, 1000);
        
        return [
            'word' => $word,
            'pronunciation' => '/ˈpleɪsˌhoʊldər/',
            'definition' => 'This is a placeholder definition generated by factory.',
            'example' => 'This is a placeholder example sentence.',
            'source' => $this->faker->randomElement(['oxford', 'cambridge', 'merriam-webster']),
            'topic' => $this->faker->randomElement($topics),
            'cefr_level' => $this->faker->randomElement(['A1', 'A2', 'B1', 'B2', 'C1', 'C2']),
            'meaning' => 'Placeholder meaning generated by factory.',
        ];
    }
}
